version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./web:/var/www/html/web
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./components:/var/www/html/components
      - ./controllers:/var/www/html/controllers
      - ./models:/var/www/html/models
      - ./web:/var/www/html/web
      - ./config:/var/www/html/config
